### ISSUE TITLE
"CLRS in short" link does not work

### ISSUE THREAD

**Issue by Auler5** [tayllan/awesome-algorithms#105]
https://github.com/tayllan/awesome-algorithms#cheat-sheets

**Comment by ZeyadKhattab** [comment]
Are you sure? it seems to be working.
I clicked [it](https://sinon.org/algorithms//#data-structures) and this was the result.

![image](https://user-images.githubusercontent.com/41998602/82912744-b7ac5e80-9f6d-11ea-9a91-21f5cd5a9a68.png)

**Comment by Auler5** [comment]
Oh yeah, now it is working for me too. Maybe the website was down at that time. Sorry for the inconvenience.

**Comment by ZeyadKhattab** [comment]
Cool, you can close the issue now
