### ISSUE TITLE
Unhandled pull requets

### ISSUE THREAD

**Issue by mostafatouny** [tayllan/awesome-algorithms#118]
Hello everyone,
First off, Let me congratulate everyone who is contributing to, or even learning from, this Awesome list.

I just wanted to address there are pull requests, made up to one year ago, and yet they are handled. Is everything okay with this repo?

Best,
Mostafa Touny

**Comment by tayllan** [comment]
Hey @mostafatouny ,

Yeah, I've neglected the repo for the past few months, but just merged all the PRs.

There's never that much going on in here, so I usually let a few PRs accumulate before looking at it.

Thanks for the concern.
