### ISSUE TITLE
Changed URL: MIT - 6-006 - Well explained algorithms.

### ISSUE THREAD

**Issue by IAFahim** [tayllan/awesome-algorithms#135]
The website has changed URL from
https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/resources/lecture-videos/

to
https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/video_galleries/lecture-videos/

![image](https://user-images.githubusercontent.com/63500913/165149916-613e2455-ef71-4204-850a-2e04469a204a.png)

Currently, results in
![image](https://user-images.githubusercontent.com/63500913/165150865-c7abb469-df2a-440a-a810-54b3da72bbea.png)

**Comment by mostafatouny** [comment]
Thanks for the note
