### ISSUE TITLE
add youtube section 

### ISSUE THREAD

**Issue by alaminrifat** [tayllan/awesome-algorithms#143]
I want to add a category named **youtube** to awesome complete tutorials available on youtube as a long duration tutorial and complete playlist.

**Comment by mostafatouny** [comment]
Thanks for your contribution. Would you explain how those playlists are different from other resources already available? This list is meant to be curated not complete

**Comment by alaminrifat** [comment]
I've found these youtube playlists very much helpful during my academic course. Everyone has a different approach to teaching. Founds in those videos teach like a classroom environment, and those playlists contain much more topics than any other free courses available. Kindly cross-check the content again.

**Comment by alaminrifat** [comment]
My pull request has been merged, but I can't find my name in the contributor list. 
can you see this issue @mostafatouny  thank you

**Comment by mostafatouny** [comment]
Your name is on commits list
