### ISSUE TITLE
Swift Algorithms Book

### ISSUE THREAD

**Issue by waynewbishop** [tayllan/awesome-algorithms#24]
Hi Folks;

Thanks for including my Swift Algorithms Github repro in your list of projects! Wanted to also let you know I've also published a book on Swift Book on algorithms that you can link to at - http://shop.waynewbishop.com.

**Comment by tayllan** [comment]
[Added](https://github.com/tayllan/awesome-algorithms/commit/54d52eee025daaa5d9298de10617b4dcfc25e0ff). Thanks, a hands-on approach is always welcome.
