### ISSUE TITLE
Another Github repository containing a Python module on algorithms and data structures

### ISSUE THREAD

**Issue by nelson-brochado** [tayllan/awesome-algorithms#41]
Here you have it, if you think it good enough to be included:

> [https://github.com/nelson-brochado/ands](https://github.com/nelson-brochado/ands)

**Comment by tayllan** [comment]
Awesome library man, thanks for the suggestion. Next time consider sending a PR straight away.

**Comment by nelson-brochado** [comment]
@tayllan Ok, regarding the PR. Anyways, I need contributors to keep developing new ds and algorithms. If you're interested or know of someone interested that wants to support it, just tell him/her or make me know.
